site_name: ITMO ICT Web Development Report
site_description: Report materials for laboratory works
docs_dir: students/k3341/Dushchenko_Daniil/docs
site_dir: students/k3341/Dushchenko_Daniil/site
theme:
  name: mkdocs
  language: ru
nav:
  - Главная: index.md
  - Лабораторная 1: lr1.md
